
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  labels:
    service: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      name: jenkins
      targetPort: 8080
    - port: 50000
      name: jnlp
      targetPort: 50000
  selector:
    service: jenkins
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  labels:
    service: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: jenkins
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jenkins
  template:
    metadata:
      labels:
        service: jenkins
    spec:
      containers:
      - image: 127.0.0.1:5000/jenkins:latest
        name: jenkins
        ports:
        - containerPort: 8080
          name: jenkins-port
          protocol: TCP
        readinessProbe:
         httpGet:
           path: /login
           port: 8080
         initialDelaySeconds: 40
         periodSeconds: 20
        securityContext:
          privileged: true
        volumeMounts:
          - name: jenkins-ps
            mountPath: "/var"
          - name: docker-sock
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: jenkins-ps
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"