apiVersion: v1
kind: Service
metadata:
  name: appservice
  labels:
    service: appservice
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
  selector:
    service: appservice
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: appdeployment
  labels:
    service: appservice
spec:
  replicas: 2
  selector:
    matchLabels:
      service: appservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: appservice
    spec:
      containers:
      - image: 303036157700.dkr.ecr.eu-central-1.amazonaws.com/samsara:latest
        name: samsara
        ports:
          - protocol: TCP
            containerPort: 9000